#+title: Emacs Config
#+author:
#+STARTUP: content

* Making sure emacs doesn't pollute my stuff :)
  This section just ensures that emacs' customize output does not squirt into my config. neato.

#+begin_src emacs-lisp
(setq custom-file (concat user-emacs-directory "auto.el"))
(if (file-exists-p custom-file)
    (load-file custom-file))
#+end_src

* Bootstrapping
  Of course, we need our package archives.
#+begin_src emacs-lisp
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
 		   ("melpa" . "https://melpa.org/packages/")
		   ("org" . "http://orgmode.org/elpa/")))
(package-initialize)
#+end_src

Now, for a bunch of other neat stuff:

#+begin_src emacs-lisp
(eval-after-load 'gnutls
  '(add-to-list 'gnutls-trustfiles "/etc/ssl/cert.pem"))
(unless (package-installed-p 'async)
  (package-refresh-contents)
  (package-install 'async))
(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))
(let ((path (concat (file-name-as-directory (concat user-emacs-directory "quelpa")) "melpa")))
  (if (not (file-exists-p path))
      (make-directory path))
  (let ((path (concat (file-name-as-directory path) "recipes")))
    (if (not (file-exists-p path))
	(make-directory path))))
(setq use-package-always-ensure t) ; docs say this is deprecated but things break when it's not included

(quelpa
 '(quelpa-use-package
   :fetcher git
   :url "https://github.com/quelpa/quelpa-use-package.git"))
(require 'quelpa-use-package)

(use-package use-package-ensure-system-package
  :ensure t)
#+end_src

* Theme + Modeline + Neat stuff
  First, all the icons. This is necessary for doom-modeline. After initalization, you MUST RUN M-x all-the-icons-install-fonts. I wish i knew a workaround at the moment. Also sets up org-bullets, and rainbow delimiters. doom-old-hope is nice, for my light theme i like to use doom-gruvbox-light.

#+begin_src emacs-lisp
(use-package all-the-icons
  :if (display-graphic-p))

(use-package humanoid-themes)

(set-face-attribute 'default nil :family "CaskaydiaCove Nerd Font Mono" :height 70)

(use-package doom-themes
  :config
  (load-theme 'doom-old-hope t))


(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))

;custom runs: after package loaded, init runs before 
(use-package doom-modeline
  :after all-the-icons
  :hook
  (after-init . doom-modeline-mode))
#+end_src

#+RESULTS:
| #[0 \300 \207 [dashboard-insert-startupify-lists] 1] | doom-modeline-mode | x-wm-set-size-hint | tramp-register-archive-file-name-handler | magit-maybe-define-global-key-bindings | table--make-cell-map |

* Getting rid of dumb keybinds

  goodbye stinky

#+begin_src emacs-lisp
(global-unset-key (kbd "C-z"))
(global-unset-key (kbd "C-x C-z"))
#+end_src

* Matlab

EEEEEEEEE
#+begin_src emacs-lisp
;; 1. MATLAB
;; (load-library "matlab-load")            ; in MELPA
(add-to-list 'load-path "/home/ched/.emacs.d/matlab-mode/matlab-emacs-src~")
(require 'matlab-load)
(autoload 'matlab-mode "matlab" "Matlab Editing Mode" t)
(setq exec-path (append exec-path '("/home/ched/mathworks/r2021b/bin")))
;; customization
(setq matlab-indent-level 4)
(setq matlab-highlight-block-match-flag t)
(setq matlab-shell-command-switches '("-nodesktop -nosplash"))

; enable CEDET---not sure what it's useful for
(matlab-cedet-setup)

; matlab-mode has support for Completion engine. Using tools in CEDET, Emacs
; will parse your M files and provide pretty good completion and code
; decoration.

; enable MLINT
(setq mlint-programs (quote ("/home/ched/mathworks/r2021b/bin/glnxa64/mlint")))
(add-hook 'matlab-mode-hook (lambda () (mlint-minor-mode 1)))
(setq matlab-show-mlint-warnings t)
(setq matlab-highlight-cross-function-variables t)
;; For R, need install.packages("lintr")


; Customize comment string to '%' only rather than '% $$$'
(setq matlab-comment-region-s "% ")
#+end_src

#+RESULTS:
: % 

* Org
** Org-Roam
  Org roam is neat, organizes everything in a folder stored in home directory titled: .orgfiles. Within this directory, you must create a folder titled "images" for org-download.

#+begin_src emacs-lisp
  (use-package org-roam
    :ensure t
    :custom
    (org-roam-directory (file-truename "~/.orgfiles"))
    (org-roam-completion-everywhere t)
    (org-roam-v2-ack t)
    :bind (("C-c n l" . org-roam-buffer-toggle)
	   ("C-c n f" . org-roam-node-find)
	   ("C-c n g" . org-roam-graph)
	   ("C-c n i" . org-roam-node-insert)
	   ;; dailies
	   ("C-c n j" . org-roam-dailies-capture-today)
	   :map org-mode-map
	   ("C-M-i"   . completion-at-point))
    :config
    (org-roam-db-autosync-mode)
  ;; if using org-roam-protocol
    (require 'org-roam-protocol))

  (setq org-roam-mode-section-functions
	(list #'org-roam-backlinks-section
	      #'org-roam-reflinks-section
	      #'org-roam-unlinked-references-section
	      ))

  (add-to-list 'display-buffer-alist
	       '("\\*org-roam\\*"
		 (display-buffer-in-direction)
		 (direction . right)
		 (window-width . 0.33)
		 (window-height . fit-window-to-buffer)))
#+end_src

And to suppress the org roam migrate warning

#+begin_src emacs-lisp
(setq org-roam-v2-ack t)
#+end_src

** Org-Download
  A neat utility to include screenshots in org files

#+begin_src emacs-lisp
(use-package org-download
  :ensure t
  :defer t
  :init
  ;; Add handlers for drag-and-drop when Org is loaded.
  (with-eval-after-load 'org
    (org-download-enable)))
#+end_src

#+RESULTS:

There is a small issue with org download at the moment, images must be on the clipboard initially. s-Y DOES NOT WORK. Screenshots are saved, yet do not get inserted into the buffer. emacs just freezes. Use screenshot machine of your choice, and use s-y to insert it into the buffer. The screenshot will also be saved to the ~/.orgfiles/images directory. Remember, you must make that directory.

This link https://github.com/abo-abo/org-download/pull/165/commits/cfc8790a28d29ddc285153977d2fc52cd96caabc Outlines changes, that will suppress the generation of the #+Download tag.

** General Org
  Showing inline images:
#+begin_src emacs-lisp
(setq org-display-inline-images t)
(setq org-redisplay-inline-images t)
(setq org-startup-with-inline-images "inlineimages")
#+end_src
  Org Agenda Path: nevermind lmfao I deleted this shit


(defun sa-find-org-file-recursively (&optional directory filext)
    "Return .org and .org_archive files recursively from DIRECTORY.
  If FILEXT is provided, return files with extension FILEXT instead."
    (interactive "DDirectory: ")
    (let* (org-file-list
	   (case-fold-search t)	      ; filesystems are case sensitive
	   (file-name-regex "^[^.#].*") ; exclude dot, autosave, and backup files
	   (filext (or filext "org$\\\|org_archive"))
	   (fileregex (format "%s\\.\\(%s$\\)" file-name-regex filext))
	   (cur-dir-list (directory-files directory t file-name-regex)))
      ;; loop over directory listing
      (dolist (file-or-dir cur-dir-list org-file-list) ; returns org-file-list
	(cond
	 ((file-regular-p file-or-dir) ; regular files
	  (if (string-match fileregex file-or-dir) ; org files
	      (add-to-list 'org-file-list file-or-dir)))
	 ((file-directory-p file-or-dir)
	  (dolist (org-file (sa-find-org-file-recursively file-or-dir filext)
			    org-file-list) ; add files found to result
	    (add-to-list 'org-file-list org-file)))))))
(setq org-agenda-text-search-extra-files
      (append (sa-find-org-file-recursively "~/.orgfiles")
              (sa-find-org-file-recursively "~/.orgfiles/daily")))

#+BEGIN_SRC emacs-lisp
(setq org-agenda-files '("~/.orgfiles/daily"))
#+END_SRC

Electric indent mode is nice, but it can be a big pain in org-mode. 

#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda() (electric-indent-local-mode -1)))
#+end_src

** Org Babel
  For org-babel, we need to load our languages. 
#+begin_src emacs-lisp
(setq org-babel-default-header-args:matlab
 '((:results . "output") (:session . "*MATLAB*")))

(org-babel-do-load-languages
'org-babel-load-languages
'((python . t) 
  (matlab . t)))
#+end_src

From some dude on stackexchange (explanation inside)

#+begin_src emacs-lisp
(require 'ob-octave-fix.el nil t)
#+end_src

#+RESULTS:

Default header args for matlab ;)

#+begin_src emacs-lisp
(setq org-babel-default-header-args:matlab
  '((:results . "output") (:session . "*MATLAB*")))
#+end_src

** Making Org Pretty 
From [[https://github.com/minad/org-modern][github]], org-modern

#+begin_src emacs-lisp results: nil
(use-package org-modern)
(add-hook 'org-mode-hook #'org-modern-mode)
(add-hook 'org-agenda-finalize-hook #'org-modern-agenda)
(setq
 ;; Edit settings
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-special-ctrl-a/e t
 org-insert-heading-respect-content t
 org-modern-block nil

 ;; Org styling, hide markup etc.
 org-hide-emphasis-markers t
 org-pretty-entities t
 org-ellipsis "…"

 ;; Agenda styling
 org-agenda-block-separator ?─
 org-agenda-time-grid
 '((daily today require-timed)
   (800 1000 1200 1400 1600 1800 2000)
   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
 org-agenda-current-time-string
 "⭠ now ─────────────────────────────────────────────────")
#+end_src 

Now, for SVG tag mode
#+begin_src emacs-lisp
(use-package svg-tag-mode)

(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make "TODO"))))))

(setq svg-tag-tags
      '(("\\(:#[A-Za-z0-9]+\\)" . ((lambda (tag)
                                     (svg-tag-make tag :beg 2))))
        ("\\(:#[A-Za-z0-9]+:\\)$" . ((lambda (tag)
                                       (svg-tag-make tag :beg 2 :end -1))))))
#+end_src


#+RESULTS:
| \(:#[A-Za-z0-9]+\)   | (lambda (tag) (svg-tag-make tag :beg 2))         |
| \(:#[A-Za-z0-9]+:\)$ | (lambda (tag) (svg-tag-make tag :beg 2 :end -1)) |

** Org Mode Keywords
Adding a few of my own org mode keywords, because progress is never really as simple as "TODO" and "DONE"

#+begin_src emacs-lisp
 (setq org-todo-keywords
  '((sequence "TODO"
      "MAYBE"
      "IN-PROG"
      "WAITING"
      "DONE"
      "DEFERRED"
      "CANCELLED")))
#+end_src

#+RESULTS:
| sequence | TODO | MAYBE | IN-PROG | WAITING | DONE | DEFERRED | CANCELLED |

* LaTeX

XeLatex - again stolen from devin. Thank u, but this doesnt work with org-ref v3 so here's this giant code block :)

#+begin_src emacs-lisp
(setq org-latex-pdf-process
					; Always need a first pass
      '("xelatex -8bit -shell-escape -interaction nonstopmode -output-directory %o %f"
					; bibtex needs some help getting started, so if there is no bibtex file, gen
					; once generated (second+ pass), could be empty. If they're empty, no need to run:
        "sh -c 'if [ ! -f %b.bbl -o -s %b.bbl ] ;then bibtex %b; fi'"
					; A few things (reference spawning/table of contents/figures/etc) change intermediary files
					; This requires a re-run or two
        "sh -c 'while grep -q -e \"File \\`%b.out\\' has changed\" -e \"Rerun to get cross-references right\" %b.log; do xelatex -8bit -shell-escape -interaction nonstopmode -output-directory %o %f ;done'"))
#+end_src

#+RESULTS:
| xelatex -8bit -shell-escape -interaction nonstopmode -output-directory %o %f | sh -c 'if [ ! -f %b.bbl -o -s %b.bbl ] ;then bibtex %b; fi' | sh -c 'while grep -q -e "File \`%b.out\' has changed" -e "Rerun to get cross-references right" %b.log; do xelatex -8bit -shell-escape -interaction nonstopmode -output-directory %o %f ;done' |
+begin_src emacs-lisp
(setq org-latex-pdf-process
      (list "latexmk -shell-escape -bibtex -f -pdf %f"))
+end_src

#+RESULTS:
| latexmk -shell-escape -bibtex -f -pdf %f |

** Latex Header
#+begin_src elisp :results silent
(require 'ob)
(require 'ob-latex)

(defvar org-babel-default-header-args:latex-header
  '((:results . "raw") (:exports . "results") (:eval . "only-export")))

(defun org-babel-expand-body:latex-header (body params)
  (org-babel-expand-body:latex body params))

(defun org-babel-execute:latex-header (body params)
  (let ((latex_output (org-babel-execute:latex body params)))
	(replace-regexp-in-string "^" "#+latex_header: " latex_output)
  ))

(defun org-babel-edit-prep:latex-header (info))

(define-derived-mode latex-header-mode latex-mode "LaTeX Header")

(provide 'ob-latex-header)
#+end_src

The following adds a =:eval only-export= attribute option to code blocks.
It is used with the above to ensure that =latex-header= blocks cannot accidentally inject results into the working =.org= buffer.

This is a direct patch from =ob-core.el=.

#+begin_src emacs-lisp :results silent
(defun org-babel-check-confirm-evaluate (info)
  "Check whether INFO allows code block evaluation.

Returns nil if evaluation is disallowed, t if it is
unconditionally allowed, and the symbol `query' if the user
should be asked whether to allow evaluation."
  (let* ((headers (nth 2 info))
	 (eval (or (cdr  (assq :eval headers))
		   (when (assq :noeval headers) "no")))
	 (eval-no (member eval '("no" "never")))
	 (export org-babel-exp-reference-buffer)
	 (eval-no-export (and export (member eval '("no-export" "never-export"))))
	 (eval-only-export (and (not export) (equal eval "only-export")))
	 (noeval (or eval-no eval-no-export eval-only-export))
	 (query (or (equal eval "query")
		    (and export (equal eval "query-export"))
		    (if (functionp org-confirm-babel-evaluate)
			(funcall org-confirm-babel-evaluate
				 ;; Language, code block body.
				 (nth 0 info)
				 (org-babel--expand-body info))
		      org-confirm-babel-evaluate))))
    (cond
     (noeval nil)
     (query 'query)
     (t t))))
#+end_src

I straight up shit myself trying to make this garbage work so i just stole it from devin who probably stole it from someone else now i can write apa yay


#+begin_src emacs-lisp
(require 'ox-publish)

(use-package org
  :ensure org-plus-contrib
  :init
  (setq org-support-shift-select t)
  (setq org-src-fontify-natively t
        org-confirm-babel-evaluate nil
        org-src-preserve-indentation t)
  :config
  (require 'ox-extra)
  (ox-extras-activate '(ignore-headlines))
  :custom
  (org-latex-listings 'minted)
  (org-latex-minted-options '(("frame" "lines") ("linenos=true")))
  (org-latex-packages-alist '(("" "minted")))
  (org-html-doctype "html5")    ; default to HTML5 output
  (org-html-html5-fancy t)              ; enable fancy new tags
  (org-html-postamble nil)              ; disable the postamble
  (org-html-postamble-format '(("en" "<hr></hr><p class=\"author\">Author: %a</p><p class=\"date\">Date: %d</p>")))
  (org-html-preamble nil)               ; disable the preamble
  (org-html-metadata-timestamp-format "%u, %B %e, %Y")
  (org-preview-latex-process-alist
   (quote
    ((dvipng :programs ("lualatex" "dvipng")
             :description "dvi > png" :message "you need to install the programs: latex and dvipng." :image-input-type "dvi" :image-output-type "png" :image-size-adjust
             (1.0 . 1.0)
             :latex-compiler
             ("lualatex -output-format dvi -interaction nonstopmode -output-directory %o %f")
             :image-converter
             ("dvipng -fg %F -bg %B -D %D -T tight -o %O %f"))
     (dvisvgm :programs ("latex" "dvisvgm")
              :description "dvi > svg" :message "you need to install the programs: latex and dvisvgm." :use-xcolor t :image-input-type "xdv" :image-output-type "svg" :image-size-adjust
              (1.7 . 1.5) :latex-compiler
              ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
              :image-converter ("dvisvgm %f -n -b min -c %S -o %O"))
     (imagemagick :programs
                  ("latex" "convert")
                  :description "pdf > png" :message "you need to install the programs: latex and imagemagick." :use-xcolor t :image-input-type "pdf" :image-output-type "png" :image-size-adjust
                  (1.0 . 1.0)
                  :latex-compiler
                  ("xelatex -no-pdf -interaction nonstopmode -output-directory %o %f")
                  :image-converter
                  ("convert -density %D -trim -antialias %f -quality 100 %O")))))
  (org-preview-latex-default-process 'dvisvgm)
  :config
  (add-hook 'org-mode-hook
            (lambda ()
              (visual-line-mode)
              (flyspell-mode)))
  (require 'ox-latex)
  (add-to-list 'org-latex-classes
               '("apa7"
                 "\\documentclass{apa7}
\\usepackage{natbib}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("IEEE"
                 "\\documentclass{IEEEtran}
\\usepackage{cite}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")))
  (add-to-list 'org-latex-classes
               '("manual"
                 "\\documentclass{memoir}
\\usepackage{natbib}
\\openany
\\usepackage{etoolbox}
\\makeatletter
\\patchcmd{\\@smemmain}{\\cleardoublepage}{\\clearpage}{}{}
\\patchcmd{\\@smemmain}{\\cleardoublepage}{\\clearpage}{}{}
\\def\\maketitle{%
  \\null
  \\thispagestyle{empty}%
  \\vfill
  \\begin{center}\\leavevmode
    \\normalfont
    {\\LARGE\\raggedleft \\@author\\par}%
    \\hrulefill\\par
    {\\huge\\raggedright \\@title\\par}%
    \\vskip 1cm
%    {\\Large \\@date\\par}%
  \\end{center}%
  \\vfill
  \\null
  \\clearpage
  }
\\frontmatter
\\makeatother
\\headstyles{memman}
\\chapterstyle{demo3}"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
  (add-to-list 'org-latex-classes
               '("memo"
                 "\\documentclass[12pt]{article}
\\usepackage{natbib}
\\makeatletter
\\renewcommand\\section{\\@startsection {section}{1}{\\z@}
                                   {-0.75ex \\@plus -0.3ex \\@minus -.1ex}
                                   {0.5ex \\@plus.02ex}
                                   {\\normalfont\\large\\bfseries}}
\\renewcommand\\subsection{\\@startsection {section}{2}{\\z@}
                                   {-0.5ex \\@plus -0.2ex \\@minus -.1ex}
                                   {0.333ex \\@plus.02ex}
                                   {\\normalfont\\normalsize\\underline}}
\\renewcommand\\subsubsection{\\@startsection {section}{3}{\\z@}
                                   {-0.25ex \\@plus -0.1ex \\@minus -0ex}
                                   {0.167ex \\@plus.02ex}
                                   {\\normalfont\\normalsize\\textit}}
\\makeatother"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
  (customize-set-value 'org-latex-hyperref-template "\\hypersetup{
 pdfauthor={%a},
 pdftitle={%t},
 pdfkeywords={%k},
 pdfsubject={%d},
 pdfcreator={%c}, 
 pdflang={%L},
pdflinkmargin=1pt,
pdfborderstyle={/S/U/W 1}}\n"))
#+end_src

** Latex Previews
Thanks again devin lmfaooooo
[[https://github.com/yangsheng6810/org-latex-impatient][org-latex-impatient]].
three
$test$four
five

#+begin_src elisp :results silent
(defun update-org-latex-fragment-scale ()
  (let ((text-scale-factor (expt text-scale-mode-step text-scale-mode-amount)))
    (plist-put org-format-latex-options :scale (* 1 text-scale-factor))
    (setq org-latex-impatient-scale (* 1 text-scale-factor))
    (org-latex-preview '(16)))
  )

;; Posframe needs to be manually configured
;; If not done, it will move the mouse to a different part of the screen
;; which is super annoying and doesn't fix anything on my wm
(use-package posframe
  :init
  (setq posframe-mouse-banish nil))

(use-package org-latex-impatient
  :after posframe
  :after org
  :hook (org-mode . org-latex-impatient-mode)
  :hook (org-mode . update-org-latex-fragment-scale)
  :init
  (setq org-latex-impatient-tex2svg-bin
        ;; location of tex2svg executable
        "~/node_modules/mathjax-node-cli/bin/tex2svg")
  (setq org-latex-impatient-border-color "white")
  (setq org-latex-impatient-user-latex-definitions
        ;; MathJax sucks and I really like using siunitx
        ;; Luckily, I can live with the most basic features
        ;; While the below is far from perfect, it is good
        ;; enough for a quick preview. C-c C-x l will give
        ;; a more acurate preview
        '("\\newcommand{\\ensuremath}[1]{#1}" 
          "\\newcommand{\\usepackage}[1]{}"
          "\\newcommand{\\yocto}{\\text{y}}"
          "\\newcommand{\\zepto}{\\text{z}}"
          "\\newcommand{\\atto}{\\text{a}}"
          "\\newcommand{\\femto}{\\text{f}}"
          "\\newcommand{\\pico}{\\text{p}}"
          "\\newcommand{\\nano}{\\text{n}}"
          "\\newcommand{\\micro}{\\mu}"
          "\\newcommand{\\milli}{\\text{m}}"
          "\\newcommand{\\centi}{\\text{c}}"
          "\\newcommand{\\deci}{\\text{d}}"
          "\\newcommand{\\deca}{\\text{da}}"
          "\\newcommand{\\hecto}{\\text{h}}"
          "\\newcommand{\\kilo}{\\text{k}}"
          "\\newcommand{\\mega}{\\text{M}}"
          "\\newcommand{\\giga}{\\text{G}}"
          "\\newcommand{\\tera}{\\text{T}}"
          "\\newcommand{\\peta}{\\text{P}}"
          "\\newcommand{\\exa}{\\text{E}}"
          "\\newcommand{\\zetta}{\\text{Z}}"
          "\\newcommand{\\yotta}{\\text{Y}}"
          "\\newcommand{\\ampere}{\\text{A}}"
          "\\newcommand{\\candela}{\\text{cd}}"
          "\\newcommand{\\kelvin}{\\text{K}}"
          "\\newcommand{\\kilogram}{\\text{kg}}"
          "\\newcommand{\\gram}{\\text{g}}"
          "\\newcommand{\\metre}{\\text{m}}"
          "\\newcommand{\\mole}{\\text{mol}}"
          "\\newcommand{\\second}{\\text{s}}"
          "\\newcommand{\\becqerel}{Bq}"
          "\\newcommand{\\degreeCelsius}{^\\circ\\text{C}}"
          "\\newcommand{\\columb}{\\text{C}}"
          "\\newcommand{\\farad}{\\text{F}}"
          "\\newcommand{\\gray}{\\text{Gy}}"
          "\\newcommand{\\hertz}{\\text{Hz}}"
          "\\newcommand{\\henry}{\\text{H}}"
          "\\newcommand{\\joule}{\\text{J}}"
          "\\newcommand{\\lumen}{\\text{lm}}"
          "\\newcommand{\\katal}{\\text{kat}}"
          "\\newcommand{\\lux}{\\text{lx}}"
          "\\newcommand{\\newton}{\\text{N}}"
          "\\newcommand{\\ohm}{\\Omega}"
          "\\newcommand{\\pascal}{\\text{Pa}}"
          "\\newcommand{\\radian}{\\text{rad}}"
          "\\newcommand{\\siemens}{\\text{S}}"
          "\\newcommand{\\sievert}{\\text{Sv}}"
          "\\newcommand{\\steradian}{\\text{sr}}"
          "\\newcommand{\\tesla}{\\text{T}}"
          "\\newcommand{\\volt}{\\text{V}}"
          "\\newcommand{\\watt}{\\text{W}}"
          "\\newcommand{\\weber}{\\text{Wb}}"
          "\\newcommand{\\SI}[2]{#1\\hspace{0.5ex}#2}")))
#+end_src

** Org-ref
#+begin_src emacs-lisp :results silent


(use-package org-ref
  :after org
  :init
  (setq org-ref-bibliography-notes "~/Documents/org-ref/notes.org"
        org-ref-default-bibliography '("~/Documents/org-ref/references.bib")
        org-ref-pdf-directory "~/Documents/org-ref/bibtex-pdfs/")
 
  (unless (file-exists-p org-ref-pdf-directory)
    (make-directory org-ref-pdf-directory t))
  (setq bibtex-completion-bibliography
	'("~/Documents/org-ref/references.bib"))
  (setq bibtex-autokey-year-length 4
        bibtex-autokey-name-year-separator "-"
        bibtex-autokey-year-title-separator "-"
        bibtex-autokey-titleword-separator "-"
        bibtex-autokey-titlewords 2
        bibtex-autokey-titlewords-stretch 1
        bibtex-autokey-titleword-length 5)
  (setq org-ref-default-citation-link "citep")
  (require 'org-ref)
  (require 'org-ref-pdf)
  (require 'org-ref-url-utils)
  )



#+end_src


* Vterm

Vterm is good, apparently.

#+begin_src fish
switch $TERM
    case xterm-256color # only in vterm
        function vterm_before --on-event fish_preexec
            vterm_cmd vterm-set-active %self
        end
end
#+end_src

#+begin_src fish
# This appends to the existing fish_prompt. Place this immediatly after a custom fish_prompt, at the end of your fish_config before other vterm integration, or anywhere inbetween
functions -c fish_prompt old_fish_prompt
function fish_prompt
    old_fish_prompt
    switch $TERM
        case xterm-256color # only in vterm
            vterm_cmd vterm-set-idle %self
    end
end
#+end_src

#+begin_src fish
function vterm_printf;
    if [ -n "$TMUX" ]
        # tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$argv"
    else if string match -q -- "screen*" "$TERM"
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$argv"
    else
        printf "\e]%s\e\\" "$argv"
    end
end

function vterm_prompt_end --description 'Used for directory tracking in vterm'
    vterm_printf '51;A'(whoami)'@'(hostname)':'(pwd)
end

function vterm_cmd --description 'Run an emacs command among the ones been defined in vterm-eval-cmds.'
    set -l vterm_elisp ()
    for arg in $argv
        set -a vterm_elisp (printf '"%s" ' (string replace -a -r '([\\\\"])' '\\\\\\\\$1' $arg))
    end
    vterm_printf '51;E'(string join '' $vterm_elisp)
end

# my custom fish_prompt with the addition in the previous code block goes somewhere in here

functions -c fish_prompt vterm_old_fish_prompt
function fish_prompt --description 'Write out the prompt; do not replace this. Instead, put this at end of your file.'
    printf "%b" (string join "\n" (vterm_old_fish_prompt))
    vterm_prompt_end
end
#+end_src


#+begin_src emacs-lisp
(use-package vterm
  :ensure-system-package fish
  :init
  (setq vterm-shell "fish")
  (setq vterm-kill-buffer-on-exit "t")
  (setq vterm-buffer-name-string "vterm %s")
  :config
  (define-key vterm-mode-map (kbd "M-<up>")    #'vterm--self-insert)
  (define-key vterm-mode-map (kbd "M-<down>")  #'vterm--self-insert)
  (define-key vterm-mode-map (kbd "M-<left>")  #'vterm--self-insert)
  (define-key vterm-mode-map (kbd "M-<right>") #'vterm--self-insert)
  (define-key vterm-mode-map (kbd "C-<left>")  #'vterm--self-insert)
  (define-key vterm-mode-map (kbd "C-<right>") #'vterm--self-insert)
  (define-key vterm-mode-map [C-backspace]     #'vterm--self-insert)
  (define-key vterm-mode-map [C-delete]        #'vterm--self-insert)
  (push (list "vterm-set-idle"   'vterm-set-idle)   vterm-eval-cmds)
  (push (list "vterm-set-active" 'vterm-set-active) vterm-eval-cmds))
#+end_src


#+RESULTS:
: t


* Autocomplete

Initially, I was gonna use eglot. Then I decided to use company. Then i just decided to use auto-complete, jedi, and irony mode.

#+begin_src emacs-lisp
  (use-package auto-complete
    :ensure t
    :init
    (progn
      (ac-config-default)
      (global-auto-complete-mode t)))

  (use-package jedi
    :ensure t
    :init
    (add-hook 'python-mode-hook 'jedi:setup)
    (add-hook 'python-mode-hook 'jedi:ac-setup))
#+end_src
Jedi requires that virtualenv is installed, via pip install virtualenv

* Yasnippet
snippets n stuff!

#+begin_src emacs-lisp
  (use-package yasnippet
    :ensure t
    :init
    (yas-global-mode t))
#+end_src
Now, add some ez default snippets

#+begin_src emacs-lisp
  (use-package yasnippet-snippets
    :ensure t)
#+end_src

* Some neat stuff
  Here, I have pdf-tools, a better pdf viewer within emacs, dired+, and a nifty dashboard configured. When setting up, make sure you have the images. Here's mine :) (definitely won't show outside of my computer lol)
It doesn't paste gifs. Whatever.

#+begin_src emacs-lisp
(use-package pdf-tools
  :config (pdf-tools-install))

(use-package dired+
  :quelpa (dired+ :fetcher github :repo "emacsmirror/dired-plus"))

(use-package dashboard
  :ensure t
  :init 
  (setq dashboard-items '((recents  . 5)))
    (setq dashboard-set-navigator t)
    (setq dashboard-startup-banner "~/emacssplash/foiled-again.gif")
    (setq dashboard-banner-logo-title "                                        ")
    :config
    (dashboard-setup-startup-hook))
#+end_src

* Misc odds-and-ends
  Initial scratch message, visual tweaks, powerline stuff (not sure i even need that, latex-mode stuff, yknow.
#+begin_src emacs-lisp
(use-package verilog-mode)

(setq initial-scratch-message "")
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(global-visual-line-mode 1)

(modify-all-frames-parameters
 '((right-divider-width . 40)
   (internal-border-width . 40)))
(dolist (face '(window-divider
                window-divider-first-pixel
                window-divider-last-pixel))
  (face-spec-reset-face face)
  (set-face-foreground face (face-attribute 'default :background)))
(set-face-background 'fringe (face-attribute 'default :background))


(setq powerline-default-separator 'arrow-fade)
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq TeX-engine 'xetex)
(setq TeX-PDF-mode t)
(setq-default TeX-master nil)
#+end_src

#+RESULTS:

* Theme Toggling
  Courtesy of Maxim Kim.
  Toggle between light mode and dark mode

#+begin_src emacs-lisp
  (defvar *haba-theme-dark* 'doom-old-hope)
  (defvar *haba-theme-light* 'modus-operandi)
  (defvar *haba-current-theme* *haba-theme-dark*)

  ;; disable other themes before loading new one
  (defadvice load-theme (before theme-dont-propagate activate)
    "Disable theme before loading new one."
    (mapc #'disable-theme custom-enabled-themes))


  (defun haba/next-theme (theme)
    (if (eq theme 'default)
	(disable-theme *haba-current-theme*)
      (progn
	(load-theme theme t)))
    (setq *haba-current-theme* theme))

  (defun haba/toggle-theme ()
    (interactive)
    (cond ((eq *haba-current-theme* *haba-theme-dark*) (haba/next-theme *haba-theme-light*))
	  ((eq *haba-current-theme* *haba-theme-light*) (haba/next-theme 'default))
	  ((eq *haba-current-theme* 'default) (haba/next-theme *haba-theme-dark*))))
  (global-set-key [C-tab] 'haba/toggle-theme)
#+end_src

* C# Weirdness
don't worry about this, honestly.

#+begin_src emacs-lisp
  (use-package powershell
       :ensure t)
#+end_src
